[build]
  command = ""
  publish = "."

# Opzionale: forza headers basilari (disattivabili)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/"
  to = "/preventivatore/mirror/"
  status = 301
  force = true
