[build]
  command = ""
  publish = "."

# Opzionale: forza headers basilari (disattivabili)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

[[redirects]]
  from = "/"
  to = "/preventivatore/mirror/"
  status = 301
  force = true

# Ensure extensionless path resolves to the HTML file for contratto page
[[redirects]]
  from = "/preventivatore/mirror/share.unionenergia.it/fv/contratto-fotovoltaico"
  to = "/preventivatore/mirror/share.unionenergia.it/fv/contratto-fotovoltaico.html"
  status = 200

[[redirects]]
  from = "/preventivatore/mirror/fv/contratto-fotovoltaico"
  to = "/preventivatore/mirror/fv/contratto-fotovoltaico.html"
  status = 200

[[headers]]
  for = "/preventivatore/mirror/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/preventivatore/Simulatore_fotovoltaico.xlsx"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
